apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: propertyquest
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: propertyquest
  source:
    repoURL: git@github.com:Momeek/propertyquest-helm.git
    targetRevision: main
    path: helm/propertyquest
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: propertyquest
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
