apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: propertyquest
  namespace: argocd
spec:
  description: propertyquest application project
  sourceRepos:
    - git@github.com:Momeek/propertyquest-helm.git
  destinations:
    - namespace: propertyquest
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
